name: 'Terraform Apply for Azure Budget'
on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Init & Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          cd environments/dev_sub_con_oldrg
          terraform init

      - name: Terraform Validate
        run: |
          cd environments/dev_sub_con_oldrg
          terraform validate

      - name: Terraform Plan
        run: |
          cd environments/dev_sub_con_oldrg
          terraform plan

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main'
        run: 
          cd environments/dev_sub_con_oldrg
          terraform apply -auto-approve
